### ISSUE TITLE
Review validation of password

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#275] opened 2018-03-27 15:41 UTC
password is "Pretty good" but is not valid

![image](https://user-images.githubusercontent.com/2777812/37978296-6a1b9af8-31ee-11e8-9c23-05bff90f28d5.png)

**Comment by IViol** [comment] 2018-03-29 15:05
Duplicate of #143

**Closed by IViol** 2018-03-29 15:05 UTC
