### ISSUE TITLE
Preview text / image

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#115] opened 2017-11-22 21:17 UTC
Change preview text:

Currently:

<img width="583" alt="jwallet preview" src="https://user-images.githubusercontent.com/25491050/33150178-5a4813b4-cfa0-11e7-92fa-835b0e9f7b19.png">

### Old text

**Jibrel Network**
The Jibrel Network provides traditional financial assets, such as currencies, bonds and equities, as standard ERC-20 tokens on the Ethereum blockchain. 

### New text

**jWallet by the Jibrel Network**
The jWallet is the first institutional-grade token storage and transaction solution. It works across devices with no download required. The jWallet is preconfigured to work with your favorite tokens.

**Comment by IViol** [comment] 2017-12-14 20:11
duplicate of #43

**Closed by IViol** 2017-12-14 20:11 UTC
