### ISSUE TITLE
jWallet TX fee 

### ISSUE THREAD

**Issue by ttabbaa** [jibrelnetwork/jwallet-web#152] opened 2017-12-18 13:04 UTC
@mezrin 
There seems to be an issue with jWallet with the Tx fee 

Transfer of 0.1 ETH , showing TX fee as 0.27616 ETH on jWallet and 0.001 on Etherescan

He then tried to send 0.1 ETH and it didn't work 

I have attached all the relevant pictures:
![tx issue tarek](https://user-images.githubusercontent.com/34570738/34107352-961661e8-e404-11e7-94af-445eed176372.jpg)
![tx issue 2](https://user-images.githubusercontent.com/34570738/34107354-963677ee-e404-11e7-889b-8bfa1a6e5373.jpg)
![tx issue 3](https://user-images.githubusercontent.com/34570738/34107355-9655f8e4-e404-11e7-9485-9da8a18c9dc4.jpg)
![tx issue 4](https://user-images.githubusercontent.com/34570738/34107356-9673acae-e404-11e7-99c5-94348481973e.jpg)
![tx issue 5](https://user-images.githubusercontent.com/34570738/34107357-96920410-e404-11e7-81b3-adcb4b6c0803.jpg)

UTC Timestamp: 
17:06:17
Friday, December 15, 2017

**Comment by mezrin** [comment] 2017-12-18 13:08
definitely a bug )

**Comment by IViol** [comment] 2017-12-21 20:35
transaction fee bug was fixed in c10f535184fd1a029acfe6b3537ea5734e3ae220

I want to note that failing of sending of transaction can't be connected with fee bug, because jwallet doesn't calculate fee for transactions itself, instead of that we request Ethereum node for estimate gas (if it was not setted by user). And this failure can't be investigated without additional info. Maybe our node was down at that moment.

But if user sent 0.1 ETH to one address, and wanted to sent 0.1 ETH back - obviously it will be impossible, because of fee for transaction.

**Comment by IViol** [comment] 2017-12-21 20:35
Closed as duplicate of #146

**Closed by IViol** 2017-12-21 20:35 UTC
Labels: bug
